### ISSUE TITLE
Initial install issue

### ISSUE THREAD

**Issue by snoiarao** [marximus/flowviz#2]
Hi! 

I'm pretty new to anaconda and having a probably stupid issue actually installing the program in the correct place. I followed the directions in the readme for installing via conda-forge, but when I try "import flowvis.flowio as flowio" like in the example binder, I get error: "ImportError: No module named flowviz.flowio".

When I do conda list, the package is clearly there! Any ideas on what I'm doing wrong?

Thanks so much!

**Comment by marximus** [comment]
Unfortunately I cannot recreate your error. I run the following commands:
`conda create -n flowviz-test   # create new environment`
`conda activate flowviz-test     # activate new environment`
`conda install -c conda-forge -c mauricemarx flowviz   # install packages`
Then I run the example notebook and I do not get this error.

Could you maybe post a screenshot of the commands you run and the error you get? Also be sure you are using "flowviz" and not "flowvis".

**Comment by snoiarao** [comment]
I think I was doing everything correctly yet still it wouldn't work when I tried your above code. I ended up just deleting all my environments and brute force restarting/re-installing and cleaning my bashsrc; now it works fine!! Thanks so much for your help!
